# Generated by Django 4.2.7 on 2026-02-01 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_count", models.IntegerField(default=0)),
                ("avg_flowrate", models.FloatField(default=0.0)),
                ("avg_pressure", models.FloatField(default=0.0)),
                ("avg_temperature", models.FloatField(default=0.0)),
                ("type_distribution", models.JSONField(default=dict)),
                (
                    "csv_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
